### ISSUE TITLE
Resource owner password flow implementation for android

### ISSUE THREAD

**Issue by satheeshyoko** [okta/okta-sdk-appauth-android#16] opened 2018-07-24 23:14 UTC
Is there any sample implementation for resource owner password implementation for android. The sample code provided only has redirection  to browser for okta from App and authenticate. Any direction or guidance is much appreciated.

**Comment by nbarbettini** [comment] 2018-10-19 20:41
@satheeshyoko We don't have documentation for this yet, but when we do I'll update this issue: https://github.com/okta/okta-sdk-appauth-android/issues/7

Closing as a duplicate of #7.

**Closed by nbarbettini** 2018-10-19 20:41 UTC
